export enum ErrorCode {
  // 汎用エラー
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  NOT_FOUND = "NOT_FOUND",
  BAD_REQUEST = "BAD_REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED",
  NOT_ACCEPTABLE = "NOT_ACCEPTABLE",
  REQUEST_TIMEOUT = "REQUEST_TIMEOUT",
  CONFLICT = "CONFLICT",

  // 認証エラー
  TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND",
  TOKEN_INVALID = "TOKEN_INVALID",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  TOKEN_USER_NOT_FOUND = "TOKEN_USER_NOT_FOUND",

  // ユーザーエラー
  USER_INVALID = "USER_INVALID",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ID_ALREADY_EXISTS = "USER_ID_ALREADY_EXISTS",
  USER_EMAIL_ALREADY_EXISTS = "USER_EMAIL_ALREADY_EXISTS",
  USER_INVALID_PASSWORD = "USER_INVALID_PASSWORD",

  // ノートエラー
  NOTE_NOT_FOUND = "NOTE_NOT_FOUND",
}

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
